controller_manager:
  ros__parameters:
    update_rate: 30
  
  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster
  
  diff_drive_controller:
    type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_attack_pinion_joint"]
    right_wheel_names: ["right_attack_pinion_joint"]
    wheel_radius: 0.09
    wheel_separation: 0.49 #0.4 + 0.045 + 0.045
    open_loop: true # Las ruedas no tienen encoders
    enable_odom_tf: false