ekf_local_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true # El robot solo se moverá en terreno llano

    map_frame: map              # Defaults to "map" if unspecified
    odom_frame: odom            # Defaults to "odom" if unspecified
    base_link_frame: base_link  # Defaults to "base_link" if unspecified
    world_frame: odom           # Defaults to the value of odom_frame if unspecified
    
    publish_tf: true

    imu0: imu/data
    imu0_config: [false, false, false,
                  false,  false,  true, # yaw
                  false, false, false,
                  false,  false,  false, # velocidad en yaw
                  false,  false,  false]
    imu0_differential: false 
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

ekf_global_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true # El robot solo se moverá en terreno llano

    map_frame: map              # Defaults to "map" if unspecified
    odom_frame: odom            # Defaults to "odom" if unspecified
    base_link_frame: base_link  # Defaults to "base_link" if unspecified
    world_frame: map           # Defaults to the value of odom_frame if unspecified
    
    publish_tf: true

    odom0: /odometry/gps
    odom0_config: [true,  true,  false, #x, y, z
                  false, false, false, #roll, pitch, yaw
                  false, false, false, #vx, vy, vz
                  false, false, false, #vr, vp, vy
                  false, false, false] #ax, ay, az
    odom0_differential: false
    odom0_queue_size: 10
    odom0_relative: false

    imu0: imu/data
    imu0_config: [false, false, false,
                  false,  false,  true, # yaw
                  false, false, false,
                  false,  false,  false, # velocidad en yaw
                  false,  false,  false]
    imu0_differential: false 
    imu0_relative: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0

    magnetic_declination_radians: 0.02443461  # Para Villamalea (1º 4')
    yaw_offset: 1.570796327  # IMU reads 0 facing magnetic north, not east
    
    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false
    wait_for_datum: false
